#!/bin/bash
# KANGA CORE - Menu Principal (Bash Wrapper) – Versão completa

colorWhite="\033[0;37m"
colorReset="\033[0m"

menu() {
    clear
    echo -e "${colorWhite}"
    php /opt/KangaCore/menu.php menu
    echo -ne "\033[1;33m > \033[0m"; read gvo
    
    if [ "$gvo" == "1" ]; then
        menuuser
    elif [ "$gvo" == "2" ]; then
        menucon
    elif [ "$gvo" == "3" ]; then
        menuferrament
    elif [ "$gvo" == "0" ]; then
        clear
        echo -e "${colorReset}"
        exit
    else
        menu
    fi
}

menuuser(){
    clear
    php /opt/KangaCore/menu.php menuusuario
    echo -ne "\033[1;33m > \033[0m"; read gvo
    
    if [ "$gvo" == "1" ]; then
        clear
        echo -ne "Usuario > "; read user
        if [ -z "$user" ]; then
            menuuser
        else
            echo -ne "Senha > "; read pass
            if [ -z "$pass" ]; then
                menuuser
            else
                echo -ne "Validade > "; read val
                if [ -z "$val" ]; then
                    menuuser
                else
                    echo -ne "Limite > "; read lim
                    if [ -z "$lim" ]; then
                        menuuser
                    else
                        php /opt/KangaCore/menu.php criaruser $val $user $pass $lim
                        clear
                        echo  "Usuario: $user"
                        echo  "Senha: $pass"
                        echo  "Validade: $val"
                        echo  "Limite: $lim"
                        echo -ne "Pressione enter para continuar"; read enter
                        menuuser
                    fi
                fi
            fi
        fi
    elif [ "$gvo" == "2" ]; then
        clear
        echo "Gerar Teste:"
        echo ""
        echo -ne "Validade em Minutos > "; read data
        if [ -z "$data" ]; then
            menuuser
        else
            clear
            php /opt/KangaCore/menu.php gerarteste $data
            echo ""
            echo -ne "Pressione enter para continuar"; read enter
            menuuser
        fi
    elif [ "$gvo" == "0" ]; then
        menu
    elif [ "$gvo" == "3" ]; then
        clear
        echo "Remover Usuario:"
        echo ""
        php /opt/KangaCore/menu.php printusers
        echo ""
        echo -ne "ID > "; read user
        if [ -z "$user" ];then
            menuuser
        else
            php /opt/KangaCore/menu.php delusernew $user
            menuuser
        fi
    elif [ "$gvo" == "4" ]; then
        clear
        echo "Usuarios online"
        echo ""
        php /opt/KangaCore/menu.php sshmonitor
        echo ""
        echo -ne "Pressione enter para continuar"; read enter
        menuuser
    elif [ "$gvo" == "5" ]; then
        clear
        echo "Alterar Data:"
        echo ""
        php /opt/KangaCore/menu.php printvalinew
        echo ""
        echo -ne "ID > "; read user
        echo -ne "Dias > "; read data
        if [ -z "$user" ]; then
            menuuser
        elif [ -z "$data" ]; then
            menuuser
        else
            php /opt/KangaCore/menu.php alterardatanew $user $data
            clear
            php /opt/KangaCore/menu.php printvalidnew $user
            echo ""
            echo -ne "Pressione enter para continuar"; read enter
            menuuser
        fi
    elif [ "$gvo" == "6" ]; then
        clear
        echo "Alterar Limite:"
        echo ""
        php /opt/KangaCore/menu.php printlimnew
        echo ""
        echo -ne "ID > "; read user
        echo -ne "Limit > "; read lim
        if [ -z "$user" ]; then
            menuuser
        elif [ -z "$lim" ]; then
            menuuser
        else
            php /opt/KangaCore/menu.php uplimitnew $user $lim
            clear
            php /opt/KangaCore/menu.php printlim2new $user
            echo ""
            echo -ne "Pressione enter para continuar"; read enter
            menuuser
        fi
    elif [ "$gvo" == "7" ]; then
        clear
        echo "Alterar Senha:"
        echo ""
        php /opt/KangaCore/menu.php printpass
        echo ""
        echo -ne "ID > "; read user
        echo -ne "Senha > "; read pass
        if [ -z "$user" ]; then
            menuuser
        elif [ -z "$pass" ]; then
            menuuser
        else
            clear
            php /opt/KangaCore/menu.php uppassnew $user $pass
            php /opt/KangaCore/menu.php printpassnew $user
            echo ""
            echo -ne "Pressione enter para continuar"; read enter
            menuuser
        fi
    elif [ "$gvo" == "8" ]; then
        clear
        echo "Relatorio de Usuarios:"
        echo ""
        php /opt/KangaCore/menu.php relatoriouser
        echo ""
        echo -ne "Pressione enter para continuar"; read enter
        menuuser
    elif [ "$gvo" == "9" ]; then
        clear
        echo "Remover Expirados:"
        echo ""
        php /opt/KangaCore/menu.php removeexpired
        echo ""
        echo -ne "Pressione enter para continuar"; read enter
        menuuser
    else
        menuuser
    fi
}

menucon(){
    clear
    php /opt/KangaCore/menu.php menuconnect
    echo -ne "\033[1;33m > \033[0m"; read gvo
    
    if [ -z "$gvo" ]; then
        menucon
    elif [ "$gvo" == "0" ]; then
        menu
    elif [ "$gvo" == "1" ]; then
        napon="$(php /opt/KangaCore/menu.php napsteron)"
        if [ "$napon" == "ON" ];then
            clear
            echo -ne "Deseja Desativar o Kanga X GO SSH? s/n: "; read sn
            if [ "$sn" == "s" ];then
                php /opt/KangaCore/menu.php napsterstop
                echo -ne "Pressione enter para continuar"; read enter
                menucon
            else
                menucon
            fi
        else
            clear
            echo -ne "Porta > "; read port
            if [ -z "$port" ]; then
                clear
                echo -ne "Porta não pode estar vazia!"; read enter
                menucon
            else
                clear
                php /opt/KangaCore/menu.php napster $port
                echo ""
                echo -ne "Pressione enter para continuar"; read enter
                menucon
            fi
        fi
    elif [ "$gvo" == "2" ]; then
        clear
        ston="$(dpkg -l | grep -q stunnel4 && echo 1 || echo 0)"
        if [ "$ston" == "1" ];then
            echo "Deseja remover o Stunnel4?"
            echo ""
            echo -ne "s/n: "; read sn
            if [ "$sn" == "s" ];then
                bash <(php /opt/KangaCore/menu.php installst)
                rm -rf /etc/stunnel
                echo ""
                echo "Stunnel4 Removido!"
                echo ""
                echo -ne "Pressione enter para continuar"; read enter
                menucon
            else
                menucon
            fi
        else
            clear
            echo -ne "Porta > "; read port
            if [ -z "$port" ]; then
                clear
                echo -ne "Porta não pode estar vazia!"; read enter
                menucon
            else
                clear
                bash <(php /opt/KangaCore/menu.php update)
                bash <(php /opt/KangaCore/menu.php upgrade)
                bash <(php /opt/KangaCore/menu.php installst)
                bash <(php /opt/KangaCore/menu.php createconf $port)
                bash <(php /opt/KangaCore/menu.php ssl_certif)
                bash <(php /opt/KangaCore/menu.php restartst)
                echo ""
                clear
                echo ""
                echo "Stunnel4 instalado porta: $port"
                echo ""
                echo -ne "Pressione enter para continuar"; read enter
                menucon
            fi
        fi
    elif [ "$gvo" == "3" ]; then
        clear
        ovpnin="$(php /opt/KangaCore/menu.php checkinstall)"
        if [ "$ovpnin" == "OK" ];then
            ovpnni="$(php /opt/KangaCore/menu.php checkovpon)"
            if [ "$ovpnni" == "OK" ];then
                clear
                echo -ne "Deseja Desativar o OVPN? (1) ou Remover? (2) 1/2: "; read sn
                if [ "$sn" == "1" ];then
                    php /opt/KangaCore/menu.php stopovpn
                    echo -ne "Pressione enter para continuar"; read enter
                    menucon
                elif [ "$sn" == "2" ];then
                    php /opt/KangaCore/menu.php stopovpn
                    apt purge openvpn -y && rm -rf /etc/openvpn
                    menucon
                else
                    menucon
                fi
            else
                clear
                bash <(php /opt/KangaCore/menu.php startovpn)
                echo -ne "Pressione enter para continuar"; read enter
                menucon
            fi
        else
            bash <(php /opt/KangaCore/menu.php ovpnin)
            php /opt/KangaCore/menu.php setupOpenVPN
            bash <(php /opt/KangaCore/menu.php ipv4)
            bash <(php /opt/KangaCore/menu.php ipv42)
            php /opt/KangaCore/menu.php client
            php /opt/KangaCore/menu.php client2
            bash <(php /opt/KangaCore/menu.php startovpn)
            echo ""
            clear
            echo ""
            echo "OpenVPN instalado porta: 1194"
            echo ""
            echo -ne "Pressione enter para continuar"; read enter
            menucon
        fi
    elif [ "$gvo" == "4" ]; then
        menuxray
    elif [ "$gvo" == "5" ]; then
        clear
        dnon="$(php /opt/KangaCore/menu.php dnstton)"
        if [ "$dnon" == "ON" ]; then
            echo "DNSTT esta ON."
            echo "1) Parar DNSTT"
            echo "2) Mostrar PubKey"
            echo "0) Voltar"
            echo -ne "> "; read op
            if [ "$op" == "1" ]; then
                php /opt/KangaCore/menu.php dnsttstop
                echo -ne "Pressione enter para continuar"; read enter
                menucon
            elif [ "$op" == "2" ]; then
                php /opt/KangaCore/menu.php dnsttpub
                echo -ne "Pressione enter para continuar"; read enter
                menucon
            else
                menucon
            fi
        else
            echo "Configurar DNSTT (SlowDNS)"
            echo ""
            echo -ne "Porta UDP (53/5300) [5300] > "; read port
            [ -z "$port" ] && port=5300
            echo -ne "NS Domain (ex: t.example.com) > "; read ns
            if [ -z "$ns" ]; then
                echo "NS Domain nao pode ficar vazio!"
                echo -ne "Pressione enter para continuar"; read enter
                menucon
            else
                echo -ne "Destino (host:porta, ex: 127.0.0.1:8000) [127.0.0.1:8000] > "; read dest
                [ -z "$dest" ] && dest="127.0.0.1:8000"
                clear
                php /opt/KangaCore/menu.php dnstt "$port" "$ns" "$dest"
                echo ""
                echo -ne "Pressione enter para continuar"; read enter
                menucon
            fi
        fi
    elif [ "$gvo" == "6" ]; then
        clear
        echo "Portas Ativas"
        echo ""
        php /opt/KangaCore/menu.php infoport
        echo ""
        echo -ne "Pressione enter para continuar"; read enter
        menucon
    else
        menucon
    fi
}

menuxray(){
    clear
    php /opt/KangaCore/menu.php menuxray
    echo -ne "\033[1;33m > \033[0m"; read option
    if [ -z "$option" ]; then
        menuxray
    elif [ "$option" == "0" ]; then
        menucon
    elif [ "$option" == "1" ]; then
        clear
        echo -ne "Nome do usuario > "; read usr
        if [ -z "$usr" ]; then
            menuxray
        else
            echo -ne "Protocolo (ws/xhttp/grpc/tcp) [ws] > "; read proto
            [ -z "$proto" ] && proto="ws"
            php /opt/KangaCore/menu.php xrayAddUser "$usr" "$proto"
            echo ""
            echo -ne "Pressione enter para continuar"; read enter
            menuxray
        fi
    elif [ "$option" == "2" ]; then
        clear
        php /opt/KangaCore/menu.php xrayListUsers
        echo ""
        echo -ne "ID ou UUID para remover > "; read ident
        if [ -n "$ident" ]; then
            php /opt/KangaCore/menu.php xrayRemoveUser "$ident"
            echo ""
            echo -ne "Pressione enter para continuar"; read enter
            menuxray
        fi
        menuxray
    elif [ "$option" == "3" ]; then
        clear
        php /opt/KangaCore/menu.php xrayListUsers
        echo ""
        echo -ne "Pressione enter para continuar"; read enter
        menuxray
    elif [ "$option" == "4" ]; then
        clear
        php /opt/KangaCore/menu.php xrayInfo
        echo ""
        echo -ne "Pressione enter para continuar"; read enter
        menuxray
    elif [ "$option" == "5" ]; then
        clear
        echo -ne "Dominio (ex: vpn.seudominio.com) > "; read dominio
        if [ -n "$dominio" ]; then
            php /opt/KangaCore/menu.php xrayCert "$dominio"
            echo ""
            chmod 777 -R /opt/KangaCoreSSL
            echo -ne "Pressione enter para continuar"; read enter
            menuxray
        fi
        menuxray
    elif [ "$option" == "6" ]; then
        clear
        echo -ne "Porta do inbound [443] > "; read p
        [ -z "$p" ] && p=443
        echo -ne "Protocolo (ws/xhttp/grpc/tcp) [ws] > "; read pr
        [ -z "$pr" ] && pr="ws"
        bash <(php /opt/KangaCore/menu.php xrayInstall)
        php /opt/KangaCore/menu.php xrayGenerateConfig "$p" "$pr"
        echo ""
        chmod 777 /usr/local/etc/xray/config.json
        echo -ne "Pressione enter para continuar"; read enter
        menuxray
    elif [ "$option" == "7" ]; then
        clear
        echo -ne "Deseja remover o Xray Core? S/n > "; read sn
        lower=$(echo "$sn" | tr '[:upper:]' '[:lower:]')
        if [[ "$lower" == "s" || "$lower" == "y" ]]; then
            bash <(php /opt/KangaCore/menu.php xrayRemove)
            echo ""
            echo -ne "Pressione enter para continuar"; read enter
            menuxray
        fi
        menuxray
    else
        menuxray
    fi
}

menuferrament(){
    clear
    php /opt/KangaCore/menu.php menuferramenta
    echo -ne "\033[1;33m > \033[0m"; read gvo
    
    if [ -z "$gvo" ]; then
        menuferrament
    elif [ "$gvo" == "0" ]; then
        menu
    elif [ "$gvo" == "1" ]; then
        clear
        echo ""
        echo -ne "Restaurar Backup? S/N > "; read att
        lowercaseInput=$(echo "$att" | tr '[:upper:]' '[:lower:]')
        if [[ "$lowercaseInput" == 'y' || "$lowercaseInput" == 's' ]]; then
            clear
            bk=$(php /opt/KangaCore/menu.php checkbackup)
            if [ "$bk" = "OK" ]; then
                php /opt/KangaCore/menu.php unpck
                php /opt/KangaCore/menu.php paswd
                php /opt/KangaCore/menu.php db
                rm -rf /root/temp
                echo ""
                echo "Restauracao concluida"
                echo ""
                echo -ne "Pressione enter para continuar"; read enter
                menuferrament
            else
                clear
                echo "backup.vps nao encontrado na pasta /root/"
                echo ""
                echo -ne "Pressione enter para continuar"; read enter
                menuferrament
            fi
        else
            menuferrament
        fi
    elif [ "$gvo" == "2" ]; then
        bdon="$(php /opt/KangaCore/menu.php badvpnon)"
        if [ "$bdon" == "ON" ];then
            clear
            echo -ne "Deseja Desativar o BadVpnX? s/n: "; read sn
            if [ "$sn" == "s" ];then
                bash <(php /opt/KangaCore/menu.php badvpnstop)
                echo -ne "Pressione enter para continuar"; read enter
                menuferrament
            else
                menuferrament
            fi
        else
            clear
            bash <(php /opt/KangaCore/menu.php badvpn)
            echo ""
            echo -ne "Pressione enter para continuar"; read enter
            menuferrament
        fi
    elif [ "$gvo" == "3" ]; then
        clear
        onnet=$(php /opt/KangaCore/menu.php checknet)
        if [ "$onnet" == "ON" ];then
            echo -ne "Deseja desativar o balanceamento? S/N > "; read sn
            lowercaseInput=$(echo "$sn" | tr '[:upper:]' '[:lower:]')
            if [[ "$lowercaseInput" == 'y' || "$lowercaseInput" == 's' ]]; then
                php /opt/KangaCore/menu.php insertnet
                echo ""
                echo -ne "Pressione enter para continuar"; read enter
                menuferrament
            else
                menuferrament
            fi
        else
            php /opt/KangaCore/menu.php insertnet
            echo ""
            echo -ne "Pressione enter para continuar"; read enter
        fi
        menuferrament
    elif [ "$gvo" == "4" ]; then
        chkuser="$(php /opt/KangaCore/menu.php checkuseron)"
        if [ "$chkuser" == "ON" ];then
            clear
            echo -ne "Deseja Desativar o CheckUser Mult APP? s/n: "; read sn
            if [ "$sn" == "s" ];then
                php /opt/KangaCore/menu.php checkuserstop
                echo -ne "Pressione enter para continuar"; read enter
                menuferrament
            else
                menuferrament
            fi
        else
            clear
            php /opt/KangaCore/menu.php checkuserstart
            echo ""
            echo -ne "Pressione enter para continuar"; read enter
            menuferrament
        fi
    elif [ "$gvo" == "5" ]; then
        clear
        bck2=$(php /opt/KangaCore/menu.php ckbkkanga)
        if [ "$bck2" == "OK" ];then
            echo -ne "Deseja Restaurar o backup? S/N > "; read sn
            lowercaseInput=$(echo "$sn" | tr '[:upper:]' '[:lower:]')
            if [[ "$lowercaseInput" == 'y' || "$lowercaseInput" == 's' ]]; then
                php /opt/KangaCore/menu.php restorebackupuser
                php /opt/KangaCore/menu.php restorebackupconnect
                rm /root/kangacoressh.json
                echo ""
                echo -ne "Pressione enter para continuar"; read enter
                menuferrament
            else
                menuferrament
            fi
        else
            echo -ne "Gerar backup do KangaCoreSSH? S/n > "; read sn
            lowercaseInput=$(echo "$sn" | tr '[:upper:]' '[:lower:]')
            if [[ "$lowercaseInput" == 'y' || "$lowercaseInput" == 's' ]]; then
                php /opt/KangaCore/menu.php createbackup
                echo ""
                echo -ne "Pressione enter para continuar"; read enter
                menuferrament
            else
                menuferrament
            fi
        fi
        menuferrament
    elif [ "$gvo" == "6" ]; then
        clear
        autock=$(php /opt/KangaCore/menu.php ckautomenu)
        if [ "$autock" == "notok" ];then
            echo -ne "Deseja Ativar o Auto Menu? S/N > "; read sn
            lowercaseInput=$(echo "$sn" | tr '[:upper:]' '[:lower:]')
            if [[ "$lowercaseInput" == 'y' || "$lowercaseInput" == 's' ]]; then
                php /opt/KangaCore/menu.php automenu
                echo ""
                echo -ne "Pressione enter para continuar"; read enter
                menuferrament
            else
                menuferrament
            fi
        else
            echo -ne "Deseja Desativar o Auto Menu? S/n > "; read sn
            lowercaseInput=$(echo "$sn" | tr '[:upper:]' '[:lower:]')
            if [[ "$lowercaseInput" == 'y' || "$lowercaseInput" == 's' ]]; then
                php /opt/KangaCore/menu.php noautomenu
                echo ""
                echo -ne "Pressione enter para continuar"; read enter
                menuferrament
            else
                menuferrament
            fi
        fi
        menuferrament
    elif [ "$gvo" == "7" ]; then
        clear
        echo "Speedtest By Ookle"
        echo ""
        php /opt/KangaCore/menu.php speedtest